### PR TITLE
Add confirmation dialog

### PR DESCRIPTION
**Pull request by ayuannisa**
Silakan di code review kak @faisalagustp

### CODE REVIEW

**Review by faisalagustp — COMMENTED** [review]
Perbaiki conflict terlebih dahulu

**Comment by ayuannisa** [comment]
Sudah kak

**Review by faisalagustp — COMMENTED** [review]
Belum. Coba pull lagi, kemudian perhatikan file ini:
.idea/modules.xml
app/app.iml
app/build.gradle
app/src/main/java/id/ac/ui/cs/lapisi/HalamanDetail.java
build.gradle
gradle/wrapper/gradle-wrapper.properties

**Comment by ayuannisa** [comment]
Sudah kak. Coba dicek lagi

**Review by faisalagustp — APPROVED** [review]
Well done.

**Pull request merged**
